using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Intrinsics.Arm;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

using Maintance.Converters;
using Maintance.DbModels;
using Maintance.Services;
using Maintance.TableAutomation.Models;

using WPFCoreEx.ValidationRules;

namespace Maintance.TableAutomation.Views
{
	/// <summary>
	/// Interaction logic for TableCreate.xaml
	/// </summary>
	public partial class TableCreationWindow : Window
	{
		private readonly ReadOnlyCollection<BindingExpressionBase> _entityBindings;
		private readonly ITableManager _tableManager;

		public TableCreationWindow(ITableManager tableManager, TableManagerSelector tableManagerSelector)
		{
			InitializeComponent();
			var c = FieldsPanel.Children;
			var defForeground = Application.Current.Resources["DefaultAutoGeneratedContentForeground"] as SolidColorBrush;
			Collection<BindingExpressionBase> bindingExpressions = new();
			foreach (var vcp in tableManager.TableColumnInfos.Where(v => !v.ViewColumnAttribute.IsAutoFill))
			{
				Control controlForProperty;
				FrameworkElement? parent = null;
				Type? t = Nullable.GetUnderlyingType(vcp.PropertyInfo.PropertyType);
				bool isNullable = t != null;
				t ??= vcp.PropertyInfo.PropertyType;
				Binding binding = new(vcp.PropertyInfo.Name)
				{
					Mode = BindingMode.TwoWay
				};
				BindingExpression currentBindingExpr;
				bool isDBModel = t.GetInterfaces().Contains(typeof(IDBModel));
				if (!isNullable || !vcp.ViewColumnAttribute.IsOptional)
				{
					if (t != typeof(string))
					{
						binding.ValidationRules.Add(new StringNotEmptyValidationRule()
						{
							MessageIfEmpty = "Обязательно к заполнению!",
							ValidationStep = ValidationStep.RawProposedValue
							//ValidatesOnTargetUpdated = true
						});
					}
					else
					{
						binding.ValidationRules.Add(new ValueNotNullValidationRule()
						{
							MessageIfNull = "Обязательно к заполнению! (string)",
							ValidationStep = ValidationStep.RawProposedValue
							//ValidatesOnTargetUpdated = true
						});
					}
				}
				if (t == typeof(DateOnly))
				{
					var dp = new DatePicker();
					binding.Converter = new DateOnlyToDateTimeConverter();
					currentBindingExpr = (BindingExpression)BindingOperations.SetBinding(dp, DatePicker.SelectedDateProperty, binding);
					controlForProperty = dp;
				}
				else if (isDBModel)
				{
					DockPanel dp = new()
					{
						LastChildFill = true
					};
					Button btn = new();
					btn.Content = new MaterialDesignThemes.Wpf.PackIcon()
					{
						Kind = MaterialDesignThemes.Wpf.PackIconKind.ArrowBottomLeftBoldBox
					};
					var dbModelTableManager = tableManagerSelector.GetITableManager(t);
					//btn.Style = (Style)Application.Current.Resources["MaterialDesignIconButton"];
					TextBox tb = new() { IsReadOnly = true, IsReadOnlyCaretVisible = true };
					currentBindingExpr = (BindingExpression)tb.SetBinding(TextBox.TextProperty, binding);
					btn.Click += (s, e) =>
					{
						if (dbModelTableManager.TrySelectEntity(out var res, this))
						{
							vcp.PropertyInfo.SetValue(currentBindingExpr.DataItem, res);		
						}
					};

					DockPanel.SetDock(btn, Dock.Right);
					DockPanel.SetDock(tb, Dock.Left);
					dp.Children.Add(btn);
					dp.Children.Add(tb);
					controlForProperty = tb;

					parent = dp;
				}
				else
				{
					var tb = new TextBox();
					binding.Converter = new EmptyStringToNullConverter();
					currentBindingExpr = (BindingExpression)BindingOperations.SetBinding(tb, TextBox.TextProperty, binding);
					controlForProperty = tb;
				}
				parent ??= controlForProperty;
				if (!string.IsNullOrEmpty(vcp.ViewColumnAttribute.ViewColumnName))
				{
					MaterialDesignThemes.Wpf.HintAssist.SetHint(controlForProperty, vcp.ViewColumnAttribute.ViewColumnName);
				}
				bindingExpressions.Add(currentBindingExpr);
				parent.Margin = new(0, 20, 0, 20);
				if (defForeground != null) controlForProperty.Foreground = defForeground;
				c.Add(parent);
			}
			_entityBindings = new(bindingExpressions);
			this._tableManager = tableManager;
		}

		private bool Created { get; set; } = false;

		private async void AddBtnClick(object sender, RoutedEventArgs e)
		{
			this.IsEnabled = false;
			bool hasError = false;
			foreach (var b in _entityBindings)
			{
				var bi = BindingOperations.GetBinding(FieldsPanel.Children[1], TextBox.TextProperty);
				b.UpdateSource();
				hasError |= b.HasError;
			}
			if (!hasError && await _tableManager.SaveWorkingEntityToDB())
			{
				this.Created = true;
				this.Hide();
			}
			this.IsEnabled = true;
		}

		private void CancelBtnClick(object sender, RoutedEventArgs e)
		{
			this.Created = false;
			this.Hide();
		}

		public bool CreateInDialog<T>(T entity, Window owner)
			where T : class
		{
			this.Owner = owner;
			this.FieldsPanel.DataContext = entity;
			this.Created = false;
			this.ShowDialog();
			return Created;
		}
	}
}
